# Change these first
owner: kim-yeonjung
repo: luniverse-monitor

sites:
  - name: Luniverse.io
    url: https://www.luniverse.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /luniverse-monitor
  logoUrl: https://console.luniverse.io/luniverse/logo_ver_blue.svg
  name: Lambda256
  introTitle: "Lambda256 Status Page"
  introMessage:  Keep Watching
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
